---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: webtime-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: webtime-deployment
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 64m
          memory: 128Mi
        maxAllowed:
          cpu: 1
          memory: 1024Mi
        controlledResources: ["cpu", "memory"]