apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtime-deployment
  labels:
    app: webtime-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webtime-app
  template:
    metadata:
      labels:
        app: webtime-app
    spec:
      containers:
      - name: masteng-webtime
        image: sangtengkorak/masteng_webtime:v1.2
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
